name: CI_React

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_react:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Build React app
      run: |
        cd frontend
        npm run build
